/**
 * GitHub integration for creating PRs with experiment results.
 *
 * Uses Octokit to interact with the GitHub API.
 */

import { Octokit } from "@octokit/rest";

// Initialize Octokit
let octokit: Octokit | null = null;

function getOctokit(): Octokit {
  if (!octokit) {
    const token = process.env.GITHUB_TOKEN;
    if (!token) {
      throw new Error("GITHUB_TOKEN environment variable is required");
    }
    octokit = new Octokit({ auth: token });
  }
  return octokit;
}

interface RepoInfo {
  owner: string;
  repo: string;
}

function parseRepoEnv(): RepoInfo {
  const repoString = process.env.GITHUB_REPO || "";
  const [owner, repo] = repoString.split("/");
  if (!owner || !repo) {
    throw new Error("GITHUB_REPO must be in format owner/repo");
  }
  return { owner, repo };
}

export interface ExperimentPRParams {
  strategyName: string;
  runId: string;
  description: string;
  metrics: {
    before?: Record<string, number>;
    after: Record<string, number>;
  };
  reportUrl?: string;
  sentryTraceUrl?: string;
}

/**
 * Create a branch for the experiment.
 */
export async function createExperimentBranch(
  strategyId: string,
  runId: string
): Promise<string> {
  const octokit = getOctokit();
  const { owner, repo } = parseRepoEnv();

  // Get the default branch's latest commit
  const { data: ref } = await octokit.git.getRef({
    owner,
    repo,
    ref: "heads/main",
  });

  const branchName = `experiment/${strategyId}/${runId}`;

  // Create the new branch
  await octokit.git.createRef({
    owner,
    repo,
    ref: `refs/heads/${branchName}`,
    sha: ref.object.sha,
  });

  return branchName;
}

/**
 * Create a PR with experiment results.
 */
export async function createExperimentPR(
  params: ExperimentPRParams
): Promise<{ prNumber: number; prUrl: string }> {
  const octokit = getOctokit();
  const { owner, repo } = parseRepoEnv();

  // Create branch
  const branchName = await createExperimentBranch(
    params.strategyName.replace(/\s+/g, "-").toLowerCase(),
    params.runId
  );

  // Build metrics table
  const metricsTable = buildMetricsTable(params.metrics);

  // Build PR body
  const body = `
## Experiment: ${params.strategyName}

### Changes
${params.description}

### Results
${metricsTable}

### Artifacts
${params.reportUrl ? `- [View Report](${params.reportUrl})` : ""}
${params.sentryTraceUrl ? `- [Sentry Trace](${params.sentryTraceUrl})` : ""}

---
*This PR was automatically generated by SignalOps*
*Run ID: ${params.runId}*
  `.trim();

  // Create PR
  const { data: pr } = await octokit.pulls.create({
    owner,
    repo,
    title: `[Experiment] ${params.strategyName}`,
    head: branchName,
    base: "main",
    body,
  });

  return {
    prNumber: pr.number,
    prUrl: pr.html_url,
  };
}

/**
 * Add a comment to an existing PR.
 */
export async function addPRComment(
  prNumber: number,
  comment: string
): Promise<void> {
  const octokit = getOctokit();
  const { owner, repo } = parseRepoEnv();

  await octokit.issues.createComment({
    owner,
    repo,
    issue_number: prNumber,
    body: comment,
  });
}

/**
 * Update PR with new experiment results.
 */
export async function updatePRWithResults(
  prNumber: number,
  metrics: Record<string, number>,
  status: "success" | "failed" | "warning"
): Promise<void> {
  const statusEmoji = {
    success: ":white_check_mark:",
    failed: ":x:",
    warning: ":warning:",
  };

  const comment = `
## ${statusEmoji[status]} Experiment Update

### Latest Metrics
| Metric | Value |
|--------|-------|
${Object.entries(metrics)
  .map(([key, value]) => `| ${key} | ${formatMetric(key, value)} |`)
  .join("\n")}

---
*Updated at ${new Date().toISOString()}*
  `.trim();

  await addPRComment(prNumber, comment);
}

/**
 * Build a markdown table comparing before/after metrics.
 */
function buildMetricsTable(metrics: {
  before?: Record<string, number>;
  after: Record<string, number>;
}): string {
  if (!metrics.before) {
    // No comparison, just show current metrics
    return `
| Metric | Value |
|--------|-------|
${Object.entries(metrics.after)
  .map(([key, value]) => `| ${formatMetricName(key)} | ${formatMetric(key, value)} |`)
  .join("\n")}
    `.trim();
  }

  // Show before/after comparison
  const rows = Object.keys(metrics.after).map((key) => {
    const before = metrics.before![key];
    const after = metrics.after[key];
    const change = calculateChange(key, before, after);

    return `| ${formatMetricName(key)} | ${formatMetric(key, before)} | ${formatMetric(key, after)} | ${change} |`;
  });

  return `
| Metric | Before | After | Change |
|--------|--------|-------|--------|
${rows.join("\n")}
  `.trim();
}

function formatMetricName(key: string): string {
  const names: Record<string, string> = {
    sharpe: "Sharpe Ratio",
    sortino: "Sortino Ratio",
    total_return: "Total Return",
    max_drawdown: "Max Drawdown",
    cagr: "CAGR",
    win_rate: "Win Rate",
    volatility: "Volatility",
  };
  return names[key] || key;
}

function formatMetric(key: string, value: number | undefined): string {
  if (value === undefined) return "N/A";

  const percentMetrics = [
    "total_return",
    "max_drawdown",
    "cagr",
    "win_rate",
    "volatility",
  ];

  if (percentMetrics.includes(key)) {
    return `${(value * 100).toFixed(1)}%`;
  }
  return value.toFixed(2);
}

function calculateChange(
  key: string,
  before: number | undefined,
  after: number
): string {
  if (before === undefined) return "N/A";

  const diff = after - before;
  const percentChange = (diff / Math.abs(before)) * 100;

  // Determine if change is positive based on metric type
  const higherIsBetter = key !== "max_drawdown" && key !== "volatility";
  const isPositive = higherIsBetter ? diff > 0 : diff < 0;

  const emoji = isPositive ? ":chart_with_upwards_trend:" : ":chart_with_downwards_trend:";
  const sign = diff > 0 ? "+" : "";

  return `${emoji} ${sign}${percentChange.toFixed(1)}%`;
}

/**
 * Get list of open experiment PRs.
 */
export async function getOpenExperimentPRs(): Promise<
  Array<{
    number: number;
    title: string;
    url: string;
    createdAt: string;
  }>
> {
  const octokit = getOctokit();
  const { owner, repo } = parseRepoEnv();

  const { data: prs } = await octokit.pulls.list({
    owner,
    repo,
    state: "open",
    head: `${owner}:experiment/`,
  });

  return prs.map((pr) => ({
    number: pr.number,
    title: pr.title,
    url: pr.html_url,
    createdAt: pr.created_at,
  }));
}
